---
- name: Add WebUpd8 apt repository.
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present update_cache=no

- name: Add WebUpd8 source repository.
  apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present update_cache=no

- name: Add key for WebUpd8 repository.
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886 state=present

- name: Update apt cache.
  apt: update_cache=yes

- name: Accepting Oracle JDK license.
  debconf: name=oracle-java8-installer question='shared/accepted-oracle-license-v1-1' value=true vtype='select'

- name: Install packages.
  apt: "name={{ item }} state=installed install_recommends=no"
  with_items: tunght13488_java_packages

- name: Remove locks.
  command: rm -rf /var/lib/apt/lists/*
